apply plugin: 'com.android.application'

android
{
	defaultConfig
	{
		applicationId 'net.albinoloverats.android.encrypt.free'
		minSdkVersion 28
		targetSdkVersion 36
		compileSdk 36
		versionCode 21
		versionName '2025.05'
	}
	signingConfigs
	{
		release
		{
		}
	}
	buildTypes
	{
		release
		{
			signingConfig signingConfigs.release
		}
		debug
		{
			debuggable true
		}
	}
	productFlavors
	{
	}
	compileOptions
	{
		targetCompatibility JavaVersion.VERSION_21
		sourceCompatibility JavaVersion.VERSION_21
	}
	namespace 'net.albinoloverats.android.encrypt.free'
}

gradle.projectsEvaluated
{
	tasks.withType(JavaCompile).tap
	{
		configureEach
		{
			options.compilerArgs << "-Xlint:deprecation"
		}
	}
}

dependencies
{
	api fileTree(dir: 'libs', include: ['*.jar'])
	api 'com.android.support:appcompat-v7:30.0.2'
	api 'com.google.android.gms:play-services-ads:22.6.0'
	api project(':encrypt')
	compileOnly "org.projectlombok:lombok:1.18.30"
	annotationProcessor 'org.projectlombok:lombok:1.18.30'
}
