#!/bin/sh

app=encrypt
version=2022.01
pkgdir=build

mkdir -p ${pkgdir}/usr/{bin,share/{encrypt,applications,man/man1,pixmaps,bash-completion/completions,zsh/functions/Completion/Unix}}
make -f Makefile
make -f Makefile install DESTDIR=${pkgdir}

mkdir ${pkgdir}/install
cp slack-desc ${pkgdir}/install

cd  ${pkgdir}
/sbin/makepkg -l y -c n ../${app}-${version}-x86_64-1aa.tgz
