name: C/C++ CI

on:
  push:
    branches: [ desktop ]
  pull_request:
    branches: [ desktop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: apt-get update && apt-get install -y libgcrypt20 libgcrypt20-dev liblzma5 liblzma-dev libcurl3-gnutls libcurl4-gnutls-dev
    - name: make
      run: make cli
    - name: self-test
      run: ./encrypt --self-test
