name: C/C++ CI

on:
  push:
    branches: [ desktop ]
  pull_request:
    branches: [ desktop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install -y gcc-14 build-essential libgcrypt20 libgcrypt20-dev liblzma5 liblzma-dev libcurl3-gnutls libcurl4-gnutls-dev
    - name: check-gcc
      run: dpkg -L gcc-14 && gcc --version
    - name: make
      run: make cli
    - name: self-test
      run: ./encrypt --self-test
